#!/bin/bash

#rebuild and restart docker

status2=`docker images -f "dangling=true" -q | wc -l`;
# Delete all none images
if [ $status2 -gt 0 ]; then
echo "images not empty, removing them...";
#docker rmi $(docker images -q)
docker rmi $(docker images -f "dangling=true" -q)
echo "done"
fi

docker-compose -f docker-compose.yml up --build -d --remove-orphans;
docker-compose ps;
